import { StandardDefinition } from '../core/standard-definition';

export const AI_GOVERNANCE_STANDARD: StandardDefinition = {
  id: 'ai-governance-standard',
  slug: 'ai-governance',
  name: 'AI Governance & Oversight Standard',
  title: 'AI Governance & Oversight Standard',
  description: 'Establishes governance controls, human oversight, prompt safety, and risk management for AI generation.',
  category: 'AI Governance',
  mediaType: 'system',
  sourceType: 'INTERNATIONAL_REFERENCE',
  version: 'v2.4.0',
  status: 'ACTIVE',
  owner: 'AI Governance Committee',
  purpose: 'To ensure responsible, transparent, and aligned AI text and visual generation across Mini Post App.',
  scope: 'Applies to all AI generation endpoints, Gemini integration, and Pollinations image rendering pipelines.',
  appliesTo: ['Creator Studio', 'Instant Post', 'Fast Post', 'Visual Brief Generator'],
  rules: [
    'Mandatory human review prior to social network publishing.',
    'System prompt safety guardrails prohibiting toxic or illegal output.',
    'Clear UI indication of AI-generated content suggestions.',
    'Auditability of prompt templates and model response parameters.',
  ],
  validationCriteria: [
    'Verified human confirmation before publication.',
    'Automated safety classification check passed.',
  ],
  acceptanceCriteria: ['Output complies with platform community standards.'],
  rejectionCriteria: ['Prohibited content category detected.'],
  severity: 'CRITICAL',
  alignmentRecords: [
    {
      frameworkId: 'ISO-42001',
      frameworkName: 'ISO/IEC 42001',
      frameworkEdition: '2023 Edition',
      mappedPrincipleOrControl: 'A.6 AI System Impact Assessment & Human Oversight',
      alignmentRationale: 'Provides human oversight and safety verification for AI output.',
      evidence: 'Mandatory human approval gate prior to posting in Creator Studio.',
      alignmentStatus: 'SUBSTANTIALLY_ALIGNED',
      lastAlignmentReview: '2026-08-01',
      nextAlignmentReview: '2026-11-01',
      alignmentOwner: 'AI Governance Lead',
    },
    {
      frameworkId: 'NIST-AI-RMF',
      frameworkName: 'NIST AI RMF',
      frameworkEdition: '1.0 Edition',
      mappedPrincipleOrControl: 'Govern 1.2 & Measure 2.3',
      alignmentRationale: 'Ensures AI risk management and prompt safety evaluation.',
      evidence: 'Safety filters and logging in prompt orchestrator.',
      alignmentStatus: 'PARTIALLY_ALIGNED',
      lastAlignmentReview: '2026-08-01',
      nextAlignmentReview: '2026-11-01',
      alignmentOwner: 'AI Governance Lead',
    },
  ],
  isPublic: true,
  publicSummary: 'Governs responsible AI prompt engineering, human oversight, safety guardrails, and auditability.',
  implementationSummary: 'Enforced via prompt orchestrator safety checks and mandatory UI review gates.',
  effectiveDate: '2026-08-01',
  reviewedDate: '2026-08-02',
  reviewFrequency: 'Quarterly',
};
