import assert from 'assert';
import { test, describe } from 'node:test';
import { FinalPostAnalyzer } from '../lib/ai-image-generator/images/finalPostAnalyzer';
import { VisualConceptGenerator } from '../lib/ai-image-generator/images/visualConceptGenerator';
import { CompositionPlanner } from '../lib/ai-image-generator/images/compositionPlanner';
import { MasterImagePromptBuilder } from '../lib/ai-image-generator/images/masterImagePromptBuilder';
import { ImagePromptValidator } from '../lib/ai-image-generator/images/ImagePromptValidator';
import { PromptRepairEngine } from '../lib/ai-image-generator/images/promptRepairEngine';
import { GeneratedImageQualityAuditor } from '../lib/ai-image-generator/images/generatedImageQualityAuditor';
import { GeneratedImageCorrectionEngine } from '../lib/ai-image-generator/images/generatedImageCorrectionEngine';
import { ControlledRegenerationManager } from '../lib/ai-image-generator/images/controlledRegenerationManager';
import { ImageAssetResult } from '@/providers/canonical-image-model';

describe('Level 21: Post-Generation Prompt Correction & Controlled Regeneration Test Suite (24 Assertions)', () => {
  const postText = 'Building scalable AI enterprise cloud infrastructure with zero-trust security.';
  const brief = FinalPostAnalyzer.analyze({ postContent: postText, platform: 'LinkedIn' });
  const concept = VisualConceptGenerator.generateConcepts(brief).selectedConcept;
  const composition = CompositionPlanner.planComposition(brief, concept).selectedComposition;
  const masterPrompt = MasterImagePromptBuilder.buildPrompt(brief, concept, composition);
  const validatedPrompt = PromptRepairEngine.repairPrompt(masterPrompt).repairedPrompt;

  const sampleAsset: ImageAssetResult = {
    id: 'asset_test_1',
    source: 'POLLINATIONS_AI',
    kind: 'AI_GENERATED',
    url: 'https://image.pollinations.ai/prompt/test?width=1200&height=675',
    previewUrl: 'https://image.pollinations.ai/prompt/test?width=1200&height=675',
    thumbnailUrl: 'https://image.pollinations.ai/prompt/test?width=1200&height=675',
    base64: 'A'.repeat(8000),
    width: 1200,
    height: 675,
    aspectRatio: '1.91:1',
    mimeType: 'image/png',
    altText: concept.primarySubject,
    creator: { name: 'Pollinations AI' },
    sourcePage: 'https://pollinations.ai',
    attribution: { text: 'Generated by Pollinations AI', url: 'https://pollinations.ai' },
    license: 'Pollinations License',
  };

  const mockProvider = async (req: any) => ({
    asset: sampleAsset,
    provider: 'pollinations_ai',
    model: 'FLUX.1-schnell',
    requestId: 'req_test_1',
    seed: 42,
    width: 1200,
    height: 675,
    mimeType: 'image/png',
    promptVersion: req.prompt.version,
    briefId: brief.id,
    conceptId: concept.id,
    compositionPlanId: composition.id,
    generationStartedAt: new Date().toISOString(),
    generationCompletedAt: new Date().toISOString(),
  });

  test('1. ControlledRegenerationManager.runRegenerationLoop() runs bounded self-correction session', async () => {
    const session = await ControlledRegenerationManager.runRegenerationLoop(brief, concept, composition, validatedPrompt, { maxAttempts: 2, providerOverride: mockProvider });
    assert.strictEqual(!!session, true);
    assert.strictEqual(session.briefId, brief.id);
  });

  test('2. Successful session ends with status: passed', async () => {
    const session = await ControlledRegenerationManager.runRegenerationLoop(brief, concept, composition, validatedPrompt, { maxAttempts: 2, providerOverride: mockProvider });
    assert.strictEqual(session.status, 'passed');
    assert.strictEqual(session.attempts.length >= 1, true);
  });

  test('3. GeneratedImageCorrectionEngine.applyPostGenerationCorrections() translates recommendations into prompt edits', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(
      { ...sampleAsset, width: 400, height: 400, aspectRatio: '1:1' },
      brief,
      concept,
      composition,
      validatedPrompt
    );
    const correction = GeneratedImageCorrectionEngine.applyPostGenerationCorrections(validatedPrompt, audit);
    assert.strictEqual(correction.corrected, true);
    assert.strictEqual(correction.correctionsApplied.length > 0, true);
  });

  test('4. Corrected prompt increments version number', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(
      { ...sampleAsset, width: 400, height: 400, aspectRatio: '1:1' },
      brief,
      concept,
      composition,
      validatedPrompt
    );
    const correction = GeneratedImageCorrectionEngine.applyPostGenerationCorrections(validatedPrompt, audit);
    assert.strictEqual(correction.correctedPrompt.version, validatedPrompt.version + 1);
  });

  test('5. Corrected prompt updates deterministic SHA-256 fingerprint', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(
      { ...sampleAsset, width: 400, height: 400, aspectRatio: '1:1' },
      brief,
      concept,
      composition,
      validatedPrompt
    );
    const correction = GeneratedImageCorrectionEngine.applyPostGenerationCorrections(validatedPrompt, audit);
    assert.notStrictEqual(correction.correctedPrompt.deterministicFingerprint, validatedPrompt.deterministicFingerprint);
  });

  test('6. Max attempts limit is strictly enforced', async () => {
    const session = await ControlledRegenerationManager.runRegenerationLoop(brief, concept, composition, validatedPrompt, { maxAttempts: 1, providerOverride: mockProvider });
    assert.strictEqual(session.maxAttempts, 1);
    assert.strictEqual(session.attempts.length <= 1, true);
  });

  test('7. User cancellation sets status: cancelled cleanly', async () => {
    const session = await ControlledRegenerationManager.runRegenerationLoop(brief, concept, composition, validatedPrompt, { maxAttempts: 2, providerOverride: mockProvider });
    const cancelled = ControlledRegenerationManager.cancelSession(session);
    assert.strictEqual(cancelled.status, 'cancelled');
    assert.strictEqual(typeof cancelled.completedAt, 'string');
  });

  test('8. bestImageVersionId tracks best generated image version', async () => {
    const session = await ControlledRegenerationManager.runRegenerationLoop(brief, concept, composition, validatedPrompt, { maxAttempts: 2, providerOverride: mockProvider });
    assert.strictEqual(typeof session.bestImageVersionId, 'string');
  });

  test('9. RegenerationSession contains required session attributes', async () => {
    const session = await ControlledRegenerationManager.runRegenerationLoop(brief, concept, composition, validatedPrompt, { maxAttempts: 2, providerOverride: mockProvider });
    assert.strictEqual(session.conceptId, concept.id);
    assert.strictEqual(session.compositionPlanId, composition.id);
    assert.strictEqual(session.initialPromptId, validatedPrompt.id);
  });

  test('10. RegenerationAttempt records durationMs and timestamp', async () => {
    const session = await ControlledRegenerationManager.runRegenerationLoop(brief, concept, composition, validatedPrompt, { maxAttempts: 2, providerOverride: mockProvider });
    const attempt = session.attempts[0];
    assert.strictEqual(typeof attempt.durationMs, 'number');
    assert.strictEqual(typeof attempt.timestamp, 'string');
  });

  test('11. Null inputs throw validation error in manager', async () => {
    await assert.rejects(
      async () => await ControlledRegenerationManager.runRegenerationLoop(null as any, concept, composition, validatedPrompt),
      (err: any) => err.message.includes('INVALID_REGENERATION_INPUT')
    );
  });

  test('12. Null inputs throw validation error in correction engine', () => {
    assert.throws(
      () => GeneratedImageCorrectionEngine.applyPostGenerationCorrections(null as any, null as any),
      (err: any) => err.message.includes('INVALID_CORRECTION_INPUT')
    );
  });

  test('13. Level 20 Generated Image Quality tests remain passing', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(sampleAsset, brief, concept, composition, validatedPrompt);
    assert.strictEqual(audit.pass, true);
  });

  test('14. Level 19 Real AI Provider Integration tests remain passing', async () => {
    const session = await ControlledRegenerationManager.runRegenerationLoop(brief, concept, composition, validatedPrompt, { maxAttempts: 1, providerOverride: mockProvider });
    assert.strictEqual(session.attempts[0].responseAsset?.kind, 'AI_GENERATED');
  });

  test('15. Level 18 Prompt Validation tests remain passing', () => {
    const val = ImagePromptValidator.validate(validatedPrompt);
    assert.strictEqual(val.valid, true);
  });

  test('16. Level 17 Master Prompt Builder tests remain passing', () => {
    assert.strictEqual(masterPrompt.briefId, brief.id);
  });

  test('17. Level 16 Composition Planner tests remain passing', () => {
    assert.strictEqual(composition.status, 'selected');
  });

  test('18. Level 15 Visual Concept Generator tests remain passing', () => {
    assert.strictEqual(concept.status, 'selected');
  });

  test('19. Level 14 Visual Brief tests remain passing', () => {
    assert.strictEqual(brief.platform, 'LinkedIn');
  });

  test('20. Clean audit without recommendations undergoes no unnecessary corrections', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(sampleAsset, brief, concept, composition, validatedPrompt);
    const cleanAudit = { ...audit, correctionRecommendations: [] };
    const correction = GeneratedImageCorrectionEngine.applyPostGenerationCorrections(validatedPrompt, cleanAudit);
    assert.strictEqual(correction.corrected, false);
    assert.strictEqual(correction.correctionsApplied.length, 0);
  });

  test('21. Target problems addressed list is populated when corrections occur', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(
      { ...sampleAsset, width: 400, height: 400, aspectRatio: '1:1' },
      brief,
      concept,
      composition,
      validatedPrompt
    );
    const correction = GeneratedImageCorrectionEngine.applyPostGenerationCorrections(validatedPrompt, audit);
    assert.strictEqual(correction.targetProblemsAddressed.includes('LOW_RESOLUTION'), true);
  });

  test('22. Session completedAt is set upon termination', async () => {
    const session = await ControlledRegenerationManager.runRegenerationLoop(brief, concept, composition, validatedPrompt, { maxAttempts: 1, providerOverride: mockProvider });
    assert.strictEqual(typeof session.completedAt, 'string');
  });

  test('23. Repaired prompt remains valid in ImagePromptValidator', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(
      { ...sampleAsset, width: 400, height: 400, aspectRatio: '1:1' },
      brief,
      concept,
      composition,
      validatedPrompt
    );
    const correction = GeneratedImageCorrectionEngine.applyPostGenerationCorrections(validatedPrompt, audit);
    const val = ImagePromptValidator.validate(correction.correctedPrompt);
    assert.strictEqual(val.valid, true);
  });

  test('24. Complete visual self-correction loop from post to verified regeneration session succeeds cleanly', async () => {
    const session = await ControlledRegenerationManager.runRegenerationLoop(brief, concept, composition, validatedPrompt, { maxAttempts: 2, providerOverride: mockProvider });
    assert.strictEqual(session.status, 'passed');
    assert.strictEqual(session.attempts.length > 0, true);
  });
});
