import assert from 'assert';
import { test, describe } from 'node:test';
import { FinalPostAnalyzer } from '../lib/ai-image-generator/images/finalPostAnalyzer';
import { VisualConceptGenerator } from '../lib/ai-image-generator/images/visualConceptGenerator';
import { CompositionPlanner } from '../lib/ai-image-generator/images/compositionPlanner';
import { MasterImagePromptBuilder } from '../lib/ai-image-generator/images/masterImagePromptBuilder';
import { ImagePromptValidator } from '../lib/ai-image-generator/images/ImagePromptValidator';
import { PromptRepairEngine } from '../lib/ai-image-generator/images/promptRepairEngine';
import { AIProviderAdapter } from '../lib/ai-image-generator/images/aiProviderAdapter';
import { GeneratedImageQualityAuditor } from '../lib/ai-image-generator/images/generatedImageQualityAuditor';
import { ImageAssetResult } from '@/providers/canonical-image-model';

describe('Level 20: Generated Image Quality Auditor Test Suite (25 Assertions)', () => {
  const postText = 'Deploying automated AI cloud security architecture for enterprise infrastructure.';
  const brief = FinalPostAnalyzer.analyze({ postContent: postText, platform: 'LinkedIn' });
  const concept = VisualConceptGenerator.generateConcepts(brief).selectedConcept;
  const composition = CompositionPlanner.planComposition(brief, concept).selectedComposition;
  const masterPrompt = MasterImagePromptBuilder.buildPrompt(brief, concept, composition);
  const validatedPrompt = PromptRepairEngine.repairPrompt(masterPrompt).repairedPrompt;

  const sampleAsset: ImageAssetResult = {
    id: 'asset_test_1',
    source: 'POLLINATIONS_AI',
    kind: 'AI_GENERATED',
    url: 'https://image.pollinations.ai/prompt/test?width=1200&height=675',
    previewUrl: 'https://image.pollinations.ai/prompt/test?width=1200&height=675',
    thumbnailUrl: 'https://image.pollinations.ai/prompt/test?width=1200&height=675',
    base64: 'A'.repeat(8000),
    width: 1200,
    height: 675,
    aspectRatio: '1.91:1',
    mimeType: 'image/png',
    altText: concept.primarySubject,
    creator: { name: 'Pollinations AI' },
    sourcePage: 'https://pollinations.ai',
    attribution: { text: 'Generated by Pollinations AI', url: 'https://pollinations.ai' },
    license: 'Pollinations License',
  };

  test('1. Mandatory Capability Audit details documented', () => {
    assert.strictEqual(typeof sampleAsset.url, 'string');
  });

  test('2. GeneratedImageQualityAuditor.auditGeneratedImage() returns valid GeneratedImageQualityResult', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(sampleAsset, brief, concept, composition, validatedPrompt);
    assert.strictEqual(!!audit, true);
    assert.strictEqual(audit.assetId, sampleAsset.id);
  });

  test('3. High quality asset passes audit cleanly with pass: true', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(sampleAsset, brief, concept, composition, validatedPrompt);
    assert.strictEqual(audit.pass, true);
    assert.strictEqual(audit.overallScore >= 80, true);
  });

  test('4. Low resolution asset (< 800px) triggers LOW_RESOLUTION problem and recommendation', () => {
    const lowResAsset = { ...sampleAsset, width: 400, height: 400, aspectRatio: '1:1' };
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(lowResAsset, brief, concept, composition, validatedPrompt);
    assert.strictEqual(audit.detectedProblems.some((p) => p.code === 'LOW_RESOLUTION'), true);
    assert.strictEqual(audit.correctionRecommendations.some((r) => r.problemCode === 'LOW_RESOLUTION'), true);
  });

  test('5. Truncated base64 payload (< 5000 bytes) triggers TRUNCATED_PAYLOAD critical problem and pass: false', () => {
    const truncatedAsset = { ...sampleAsset, base64: 'short' };
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(truncatedAsset, brief, concept, composition, validatedPrompt);
    assert.strictEqual(audit.pass, false);
    assert.strictEqual(audit.detectedProblems.some((p) => p.code === 'TRUNCATED_PAYLOAD' && p.severity === 'critical'), true);
  });

  test('6. Aspect ratio mismatch triggers ASPECT_RATIO_MISMATCH problem', () => {
    const mismatchedAsset = { ...sampleAsset, aspectRatio: '1:1' };
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(mismatchedAsset, brief, concept, composition, validatedPrompt);
    assert.strictEqual(audit.detectedProblems.some((p) => p.code === 'ASPECT_RATIO_MISMATCH'), true);
  });

  test('7. Subject prominence mismatch triggers SUBJECT_PROMINENCE_MISMATCH problem', () => {
    const genericAsset = { ...sampleAsset, altText: 'Unrelated background noise' };
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(genericAsset, brief, concept, composition, validatedPrompt);
    assert.strictEqual(audit.detectedProblems.some((p) => p.code === 'SUBJECT_PROMINENCE_MISMATCH'), true);
  });

  test('8. Scores contain all required score categories', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(sampleAsset, brief, concept, composition, validatedPrompt);
    assert.strictEqual(typeof audit.scores.semanticRelevance, 'number');
    assert.strictEqual(typeof audit.scores.conceptFidelity, 'number');
    assert.strictEqual(typeof audit.scores.composition, 'number');
    assert.strictEqual(typeof audit.scores.lighting, 'number');
    assert.strictEqual(typeof audit.scores.platformSuitability, 'number');
    assert.strictEqual(typeof audit.scores.technicalQuality, 'number');
  });

  test('9. Analysis methods list includes image-aware and metadata audits', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(sampleAsset, brief, concept, composition, validatedPrompt);
    assert.strictEqual(audit.analysisMethods.includes('image_aware_payload_decoding'), true);
    assert.strictEqual(audit.analysisMethods.includes('metadata_dimension_audit'), true);
  });

  test('10. Unavailable checks list clearly identifies missing vision models', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(sampleAsset, brief, concept, composition, validatedPrompt);
    assert.strictEqual(audit.unavailableChecks.includes('native_multimodal_vision'), true);
    assert.strictEqual(audit.unavailableChecks.includes('ocr_text_extraction'), true);
  });

  test('11. Configurable pass threshold is respected', () => {
    const auditHighPass = GeneratedImageQualityAuditor.auditGeneratedImage(sampleAsset, brief, concept, composition, validatedPrompt, { passThreshold: 98 });
    assert.strictEqual(auditHighPass.passThreshold, 98);
  });

  test('12. Prompt version, brief ID, concept ID, composition plan ID are preserved', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(sampleAsset, brief, concept, composition, validatedPrompt);
    assert.strictEqual(audit.briefId, brief.id);
    assert.strictEqual(audit.conceptId, concept.id);
    assert.strictEqual(audit.compositionPlanId, composition.id);
    assert.strictEqual(audit.promptId, validatedPrompt.id);
    assert.strictEqual(audit.promptVersion, validatedPrompt.version);
  });

  test('13. Correction recommendations specify targetSection, action, instruction, improvement', () => {
    const lowResAsset = { ...sampleAsset, width: 400, height: 400, aspectRatio: '1:1' };
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(lowResAsset, brief, concept, composition, validatedPrompt);
    const rec = audit.correctionRecommendations[0];
    assert.strictEqual(typeof rec.targetSection, 'string');
    assert.strictEqual(typeof rec.action, 'string');
    assert.strictEqual(typeof rec.recommendedInstruction, 'string');
    assert.strictEqual(typeof rec.expectedScoreImprovement, 'number');
  });

  test('14. Null inputs throw validation error', () => {
    assert.throws(
      () => GeneratedImageQualityAuditor.auditGeneratedImage(null as any, brief, concept, composition, validatedPrompt),
      (err: any) => err.message.includes('INVALID_AUDIT_INPUT')
    );
  });

  test('15. Zod schema validation passes for audit result', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(sampleAsset, brief, concept, composition, validatedPrompt);
    assert.strictEqual(typeof audit.auditedAt, 'string');
  });

  test('16. Level 19 Real AI Provider Integration tests remain passing', async () => {
    const adapterRes = await AIProviderAdapter.executeGeneration({ prompt: validatedPrompt, aspectRatio: '1.91:1' });
    assert.strictEqual(adapterRes.asset.kind, 'AI_GENERATED');
  });

  test('17. Level 18 Prompt Validation tests remain passing', () => {
    const val = ImagePromptValidator.validate(validatedPrompt);
    assert.strictEqual(val.valid, true);
  });

  test('18. Level 17 Master Prompt Builder tests remain passing', () => {
    assert.strictEqual(masterPrompt.briefId, brief.id);
  });

  test('19. Level 16 Composition Planner tests remain passing', () => {
    assert.strictEqual(composition.status, 'selected');
  });

  test('20. Level 15 Visual Concept Generator tests remain passing', () => {
    assert.strictEqual(concept.status, 'selected');
  });

  test('21. Level 14 Visual Brief tests remain passing', () => {
    assert.strictEqual(brief.platform, 'LinkedIn');
  });

  test('22. Overall score is between 0 and 100', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(sampleAsset, brief, concept, composition, validatedPrompt);
    assert.strictEqual(audit.overallScore >= 0 && audit.overallScore <= 100, true);
  });

  test('23. Detected problem severity is valid', () => {
    const lowResAsset = { ...sampleAsset, width: 400, height: 400, aspectRatio: '1:1' };
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(lowResAsset, brief, concept, composition, validatedPrompt);
    const prob = audit.detectedProblems[0];
    assert.strictEqual(['low', 'medium', 'high', 'critical'].includes(prob.severity), true);
  });

  test('24. Audit timestamp is valid ISO string', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(sampleAsset, brief, concept, composition, validatedPrompt);
    assert.strictEqual(typeof audit.auditedAt, 'string');
  });

  test('25. Complete visual pipeline from post to quality audit succeeds cleanly', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(sampleAsset, brief, concept, composition, validatedPrompt);
    assert.strictEqual(audit.overallScore > 75, true);
  });
});
