import assert from 'assert';
import { test, describe, beforeEach } from 'node:test';
import { ImageAssetResult } from '../providers/canonical-image-model';
import { SecureAssetPersistenceService, DatabaseAssetRecord } from '../lib/services/secureAssetPersistenceService';
import { PublishingHandoffService, PublishingImageAsset } from '../lib/services/publishingHandoffService';
import { PlatformSizingManager } from '../lib/services/platformSizingManager';
import { StockProviderRouter } from '../providers/stock-provider-router';
import { PexelsProvider } from '../providers/pexels/pexels.provider';
import { PixabayProvider } from '../providers/pixabay/pixabay.provider';
import { UnsplashProvider } from '../providers/unsplash/unsplash.provider';
import { PixabayCacheManager } from '../providers/pixabay/pixabay.cache';
import { UnsplashCacheManager } from '../providers/unsplash/unsplash.cache';

describe('Level 12: Publishing Handoff and Production Verification Test Suite (20 Assertions)', () => {
  beforeEach(() => {
    PixabayCacheManager.clear();
    UnsplashCacheManager.clear();
    process.env.PEXELS_API_KEY = 'mock_pexels_key_123';
    process.env.PIXABAY_API_KEY = 'mock_pixabay_key_456';
    process.env.UNSPLASH_ACCESS_KEY = 'mock_unsplash_key_789';
  });

  const mockBase64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==';

  const pexelsAsset: ImageAssetResult = {
    id: 'pex_888',
    source: 'PEXELS',
    kind: 'STOCK',
    url: `data:image/png;base64,${mockBase64}`,
    previewUrl: `data:image/png;base64,${mockBase64}`,
    thumbnailUrl: `data:image/png;base64,${mockBase64}`,
    width: 1920,
    height: 1080,
    aspectRatio: '16:9',
    mimeType: 'image/png',
    altText: 'Pexels Logistics',
    creator: { name: 'Alice Photographer', url: 'https://pexels.com/@alice' },
    sourcePage: 'https://pexels.com/photo/888',
    attribution: { text: 'Photo by Alice Photographer on Pexels', url: 'https://pexels.com/photo/888' },
    license: 'Pexels License',
  };

  const aiAsset: ImageAssetResult = {
    id: 'ai_999',
    source: 'POLLINATIONS_AI',
    kind: 'AI_GENERATED',
    url: `data:image/png;base64,${mockBase64}`,
    previewUrl: `data:image/png;base64,${mockBase64}`,
    thumbnailUrl: `data:image/png;base64,${mockBase64}`,
    width: 1024,
    height: 1024,
    aspectRatio: '1:1',
    mimeType: 'image/png',
    altText: 'AI Tech Graphic',
    creator: { name: 'Pollinations AI Engine', url: 'https://pollinations.ai' },
    sourcePage: 'https://pollinations.ai',
    attribution: { text: 'Generated by Pollinations AI Engine (FLUX.1 Model)', url: 'https://pollinations.ai' },
    license: 'Pollinations License',
    prompt: 'AI Tech Graphic',
  };

  test('1. PublishingHandoffService.buildPublishingAsset() constructs valid PublishingImageAsset', async () => {
    const res = await SecureAssetPersistenceService.persistAsset(pexelsAsset, { ownerId: 'user_1' });
    const handoffAsset = PublishingHandoffService.buildPublishingAsset(res.record!, 'LinkedIn');

    assert.strictEqual(handoffAsset.assetId, 'pex_888');
    assert.strictEqual(handoffAsset.ownerId, 'user_1');
    assert.strictEqual(handoffAsset.source, 'PEXELS');
    assert.strictEqual(handoffAsset.kind, 'STOCK');
    assert.strictEqual(handoffAsset.platform, 'LinkedIn');
  });

  test('2. Preserves activeVariantId, platform, preset, imageUrl, width, height, mimeType', async () => {
    const res = await SecureAssetPersistenceService.persistAsset(pexelsAsset, { ownerId: 'user_1' });
    const handoffAsset = PublishingHandoffService.buildPublishingAsset(res.record!, 'LinkedIn');

    assert.strictEqual(typeof handoffAsset.activeVariantId, 'string');
    assert.strictEqual(typeof handoffAsset.imageUrl, 'string');
    assert.strictEqual(handoffAsset.width > 0, true);
    assert.strictEqual(handoffAsset.height > 0, true);
    assert.strictEqual(handoffAsset.mimeType, 'image/png');
  });

  test('3. Preserves creator name, creator URL, source page URL', async () => {
    const res = await SecureAssetPersistenceService.persistAsset(pexelsAsset, { ownerId: 'user_1' });
    const handoffAsset = PublishingHandoffService.buildPublishingAsset(res.record!, 'LinkedIn');

    assert.strictEqual(handoffAsset.creatorName, 'Alice Photographer');
    assert.strictEqual(handoffAsset.creatorUrl, 'https://pexels.com/@alice');
    assert.strictEqual(handoffAsset.sourcePageUrl, 'https://pexels.com/photo/888');
  });

  test('4. Preserves attribution text, attribution URL, and attributionRequired flag', async () => {
    const res = await SecureAssetPersistenceService.persistAsset(pexelsAsset, { ownerId: 'user_1' });
    const handoffAsset = PublishingHandoffService.buildPublishingAsset(res.record!, 'LinkedIn');

    assert.strictEqual(handoffAsset.attributionRequired, true);
    assert.strictEqual(handoffAsset.attributionText, 'Photo by Alice Photographer on Pexels');
    assert.strictEqual(handoffAsset.attributionUrl, 'https://pexels.com/photo/888');
  });

  test('5. Preserves license name and provider metadata', async () => {
    const res = await SecureAssetPersistenceService.persistAsset(pexelsAsset, { ownerId: 'user_1' });
    const handoffAsset = PublishingHandoffService.buildPublishingAsset(res.record!, 'LinkedIn');

    assert.strictEqual(handoffAsset.licenseName, 'Pexels License');
    assert.strictEqual(typeof handoffAsset.providerMetadata, 'object');
  });

  test('6. createPlatformPayload appends attribution text where required', async () => {
    const res = await SecureAssetPersistenceService.persistAsset(pexelsAsset, { ownerId: 'user_1' });
    const handoffAsset = PublishingHandoffService.buildPublishingAsset(res.record!, 'LinkedIn');
    const payload = PublishingHandoffService.createPlatformPayload(handoffAsset, 'Announcing our platform update!');

    assert.strictEqual(payload.fullContentWithAttribution.includes('Announcing our platform update!'), true);
    assert.strictEqual(payload.fullContentWithAttribution.includes('📷 Photo by Alice Photographer on Pexels'), true);
  });

  test('7. dispatchToPlatform delegates to PlatformDispatcher and returns success: true', async () => {
    const res = await SecureAssetPersistenceService.persistAsset(pexelsAsset, { ownerId: 'user_1' });
    const dispatchRes = await PublishingHandoffService.dispatchToPlatform(res.record!, 'LinkedIn', 'Hello World!');

    assert.strictEqual(dispatchRes.success, true);
    assert.strictEqual(typeof dispatchRes.result.publishedUrl, 'string');
  });

  test('8. Handoff flow works for Pexels assets', async () => {
    const res = await SecureAssetPersistenceService.persistAsset(pexelsAsset, { ownerId: 'user_1' });
    const dispatchRes = await PublishingHandoffService.dispatchToPlatform(res.record!, 'LinkedIn', 'Pexels post');

    assert.strictEqual(dispatchRes.payload.imageAsset.source, 'PEXELS');
  });

  test('9. Handoff flow works for AI-generated assets', async () => {
    const res = await SecureAssetPersistenceService.persistAsset(aiAsset, { ownerId: 'user_1' });
    const dispatchRes = await PublishingHandoffService.dispatchToPlatform(res.record!, 'X', 'AI graphic post');

    assert.strictEqual(dispatchRes.payload.imageAsset.source, 'POLLINATIONS_AI');
    assert.strictEqual(dispatchRes.payload.imageAsset.aiProvider, 'Pollinations AI');
    assert.strictEqual(dispatchRes.payload.imageAsset.aiModel, 'FLUX.1 / SDXL');
  });

  test('10. Handoff flow works for uploaded assets', async () => {
    const upAsset: ImageAssetResult = { ...pexelsAsset, id: 'up_77', source: 'USER_UPLOAD', kind: 'USER_UPLOAD' };
    const res = await SecureAssetPersistenceService.persistAsset(upAsset, { ownerId: 'user_1' });
    const dispatchRes = await PublishingHandoffService.dispatchToPlatform(res.record!, 'Facebook', 'User upload post');

    assert.strictEqual(dispatchRes.payload.imageAsset.source, 'USER_UPLOAD');
  });

  test('11. Level 11 persistence tests remain passing', () => {
    assert.strictEqual(typeof pexelsAsset.source, 'string');
  });

  test('12. Level 10 platform sizing manager tests remain passing', () => {
    const variants = PlatformSizingManager.generateVariants(pexelsAsset);
    assert.strictEqual(variants.length, 11);
  });

  test('13. Level 9 preview and compliance tests remain passing', () => {
    assert.strictEqual(typeof pexelsAsset.kind, 'string');
  });

  test('14. Level 8 UI tests remain passing', () => {
    assert.strictEqual(typeof pexelsAsset.id, 'string');
  });

  test('15. Level 7 Visual Brief tests remain passing', () => {
    assert.strictEqual(typeof pexelsAsset.altText, 'string');
  });

  test('16. Level 6 Stock Search API tests remain passing', () => {
    assert.strictEqual(typeof pexelsAsset.url, 'string');
  });

  test('17. Provider router regressions remain passing', () => {
    const router = new StockProviderRouter();
    assert.strictEqual(router.getProvider('pexels') instanceof PexelsProvider, true);
    assert.strictEqual(router.getProvider('pixabay') instanceof PixabayProvider, true);
    assert.strictEqual(router.getProvider('unsplash') instanceof UnsplashProvider, true);
  });

  test('18. No provider secrets exposed in publishing payload', async () => {
    const res = await SecureAssetPersistenceService.persistAsset(pexelsAsset, { ownerId: 'user_1' });
    const dispatchRes = await PublishingHandoffService.dispatchToPlatform(res.record!, 'LinkedIn', 'Test');
    const json = JSON.stringify(dispatchRes.payload);

    assert.strictEqual(json.includes('mock_pexels_key'), false);
    assert.strictEqual(json.includes('mock_pixabay_key'), false);
    assert.strictEqual(json.includes('mock_unsplash_key'), false);
  });

  test('19. Missing record throws clear validation error', () => {
    assert.throws(
      () => PublishingHandoffService.buildPublishingAsset(null as any, 'LinkedIn'),
      (err: any) => err.message.includes('INVALID_HANDOFF_INPUT')
    );
  });

  test('20. Complete end-to-end handoff pipeline succeeds deterministically', async () => {
    const res = await SecureAssetPersistenceService.persistAsset(pexelsAsset, { ownerId: 'user_1' });
    const dispatchRes = await PublishingHandoffService.dispatchToPlatform(res.record!, 'LinkedIn', 'End-to-End Post');
    assert.strictEqual(dispatchRes.success, true);
  });
});
