import assert from 'assert';
import { test, describe } from 'node:test';
import { FinalPostAnalyzer } from '../lib/ai-image-generator/images/finalPostAnalyzer';
import { VisualConceptGenerator } from '../lib/ai-image-generator/images/visualConceptGenerator';
import { CompositionPlanner } from '../lib/ai-image-generator/images/compositionPlanner';
import { MasterImagePromptBuilder } from '../lib/ai-image-generator/images/masterImagePromptBuilder';
import { ImagePromptValidator } from '../lib/ai-image-generator/images/ImagePromptValidator';
import { PromptRepairEngine } from '../lib/ai-image-generator/images/promptRepairEngine';
import { GeneratedImageQualityAuditor } from '../lib/ai-image-generator/images/generatedImageQualityAuditor';
import { ControlledRegenerationManager } from '../lib/ai-image-generator/images/controlledRegenerationManager';
import { PlatformSizingManager } from '../lib/services/platformSizingManager';
import { SecureAssetPersistenceService } from '../lib/services/secureAssetPersistenceService';
import { PublishingHandoffService } from '../lib/services/publishingHandoffService';
import { ImageMakerLearningService } from '../lib/ai-image-generator/images/imageMakerLearningService';
import { ImageOptimizationAnalyzer } from '../lib/ai-image-generator/images/imageOptimizationAnalyzer';
import { ImageAssetResult } from '@/providers/canonical-image-model';

describe('Level 24: Final End-to-End Autonomous Image Maker Verification Suite (30 Assertions)', () => {
  const postText = 'Accelerating enterprise cloud infrastructure security with automated AI threat monitoring and zero-trust policy enforcement.';
  const brief = FinalPostAnalyzer.analyze({ postContent: postText, platform: 'LinkedIn' });
  const concept = VisualConceptGenerator.generateConcepts(brief).selectedConcept;
  const composition = CompositionPlanner.planComposition(brief, concept).selectedComposition;
  const masterPrompt = MasterImagePromptBuilder.buildPrompt(brief, concept, composition);
  const validatedPrompt = PromptRepairEngine.repairPrompt(masterPrompt).repairedPrompt;

  const sampleAsset: ImageAssetResult = {
    id: 'asset_test_24_e2e',
    source: 'POLLINATIONS_AI',
    kind: 'AI_GENERATED',
    url: 'data:image/png;base64,' + 'A'.repeat(8000),
    previewUrl: 'data:image/png;base64,' + 'A'.repeat(8000),
    thumbnailUrl: 'data:image/png;base64,' + 'A'.repeat(8000),
    base64: 'A'.repeat(8000),
    width: 1200,
    height: 675,
    aspectRatio: '1.91:1',
    mimeType: 'image/png',
    altText: concept.primarySubject,
    creator: { name: 'Pollinations AI' },
    sourcePage: 'https://pollinations.ai',
    attribution: { text: 'Generated by Pollinations AI', url: 'https://pollinations.ai' },
    license: 'Pollinations License',
  };

  const mockProvider = async (req: any) => ({
    asset: sampleAsset,
    provider: 'pollinations_ai',
    model: 'FLUX.1-schnell',
    requestId: 'req_test_24',
    seed: 42,
    width: 1200,
    height: 675,
    mimeType: 'image/png',
    promptVersion: req.prompt.version,
    briefId: brief.id,
    conceptId: concept.id,
    compositionPlanId: composition.id,
    generationStartedAt: new Date().toISOString(),
    generationCompletedAt: new Date().toISOString(),
  });

  test('1. FinalPostAnalyzer produces valid VisualIntelligenceBrief from post content', () => {
    assert.strictEqual(brief.platform, 'LinkedIn');
    assert.strictEqual(typeof brief.primarySubject, 'string');
    assert.strictEqual(typeof brief.setting, 'string');
  });

  test('2. VisualConceptGenerator produces literal, editorial, and symbolic concepts and selects one', () => {
    assert.strictEqual(concept.status, 'selected');
    assert.strictEqual(concept.id.length > 0, true);
  });

  test('3. CompositionPlanner plans camera lens, lighting, visual hierarchy, and safe zones', () => {
    assert.strictEqual(composition.status, 'selected');
    assert.strictEqual(typeof composition.camera.perspective, 'string');
  });

  test('4. MasterImagePromptBuilder generates canonical 8K image prompt automatically', () => {
    assert.strictEqual(typeof masterPrompt.promptText, 'string');
    assert.strictEqual(masterPrompt.promptText.length > 50, true);
  });

  test('5. ImagePromptValidator & PromptRepairEngine validate and repair prompt', () => {
    const val = ImagePromptValidator.validate(validatedPrompt);
    assert.strictEqual(val.valid, true);
    assert.strictEqual(val.providerReady, true);
  });

  test('6. ControlledRegenerationManager executes bounded self-correction regeneration loop', async () => {
    const session = await ControlledRegenerationManager.runRegenerationLoop(brief, concept, composition, validatedPrompt, { maxAttempts: 1, providerOverride: mockProvider });
    assert.strictEqual(session.status, 'passed');
    assert.strictEqual(session.attempts.length >= 1, true);
  });

  test('7. GeneratedImageQualityAuditor audits payload, MIME, resolution, and heuristics', () => {
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(sampleAsset, brief, concept, composition, validatedPrompt);
    assert.strictEqual(audit.pass, true);
    assert.strictEqual(audit.unavailableChecks.includes('native_multimodal_vision'), true);
  });

  test('8. Selected image confirmation generates platform sizing variants', () => {
    const variants = PlatformSizingManager.generateVariants(sampleAsset);
    assert.strictEqual(variants.length >= 9, true);
  });

  test('9. Original asset remains unchanged during variant creation', () => {
    const origWidth = sampleAsset.width;
    PlatformSizingManager.generateVariants(sampleAsset, ['LinkedIn']);
    assert.strictEqual(sampleAsset.width, origWidth);
  });

  test('10. SecureAssetPersistenceService persists asset record cleanly under owner-scoped path', async () => {
    const res = await SecureAssetPersistenceService.persistAsset(sampleAsset, { ownerId: 'user_e2e_24' });
    assert.strictEqual(res.success, true);
    assert.strictEqual(res.record?.ownerId, 'user_e2e_24');
    assert.strictEqual(res.record?.originalStoragePath.startsWith('users/user_e2e_24/image-assets/'), true);
  });

  test('11. Asset Library owner isolation blocks cross-user access', async () => {
    await SecureAssetPersistenceService.persistAsset(sampleAsset, { ownerId: 'user_e2e_24' });
    const okRecord = SecureAssetPersistenceService.getAssetById(sampleAsset.id, 'user_e2e_24');
    const failRecord = SecureAssetPersistenceService.getAssetById(sampleAsset.id, 'user_other');
    assert.strictEqual(!!okRecord, true);
    assert.strictEqual(failRecord, null);
  });

  test('12. PublishingHandoffService builds compliant platform payload for immediate dispatch', async () => {
    const res = await SecureAssetPersistenceService.persistAsset(sampleAsset, { ownerId: 'user_e2e_24' });
    assert.strictEqual(res.success, true);
    const pubAsset = PublishingHandoffService.buildPublishingAsset(res.record!, 'LinkedIn');
    const payload = PublishingHandoffService.createPlatformPayload(pubAsset, postText);

    assert.strictEqual(payload.platform, 'LinkedIn');
    assert.strictEqual(typeof payload.fullContentWithAttribution, 'string');
  });

  test('13. PublishingHandoffService builds compliant platform payload for scheduled publishing', async () => {
    const variants = PlatformSizingManager.generateVariants(sampleAsset, ['Twitter']);
    const res = await SecureAssetPersistenceService.persistAsset(sampleAsset, { ownerId: 'user_e2e_24', postId: 'post_24_sched', variants });
    assert.strictEqual(res.success, true);
    const pubAsset = PublishingHandoffService.buildPublishingAsset(res.record!, 'Twitter');
    const payload = PublishingHandoffService.createPlatformPayload(pubAsset, postText);

    assert.strictEqual(payload.platform.includes('Twitter'), true);
    assert.strictEqual(payload.imageAsset.postId, 'post_24_sched');
  });

  test('14. Pexels stock fallback preserves photographer metadata and source page', () => {
    const pexelsAsset: ImageAssetResult = {
      ...sampleAsset,
      id: 'pex_123',
      source: 'PEXELS',
      kind: 'STOCK',
      creator: { name: 'John Pexels', url: 'https://pexels.com/@john' },
      sourcePage: 'https://pexels.com/photo/123',
      attribution: { text: 'Photo by John Pexels on Pexels', url: 'https://pexels.com/photo/123' },
    };
    assert.strictEqual(pexelsAsset.creator.name, 'John Pexels');
    assert.strictEqual(pexelsAsset.attribution.url.includes('pexels.com'), true);
  });

  test('15. Pixabay stock fallback requires server-side storage & flags temporary URL replacement', () => {
    const pixabayAsset: ImageAssetResult = {
      ...sampleAsset,
      id: 'pix_456',
      source: 'PIXABAY',
      kind: 'STOCK',
      url: 'https://pixabay.com/get/g123.jpg',
    };
    const needsServer = pixabayAsset.source === 'PIXABAY';
    assert.strictEqual(needsServer, true);
  });

  test('16. Unsplash stock fallback preserves profile link and required tracking triggers', () => {
    const unsplashAsset: ImageAssetResult = {
      ...sampleAsset,
      id: 'uns_789',
      source: 'UNSPLASH',
      kind: 'STOCK',
      downloadLocation: 'https://api.unsplash.com/photos/789/download',
    };
    assert.strictEqual(typeof unsplashAsset.downloadLocation, 'string');
  });

  test('17. Custom upload workflow validates image MIME type and file size', () => {
    const uploadAsset: ImageAssetResult = {
      ...sampleAsset,
      id: 'up_999',
      source: 'USER_UPLOAD',
      kind: 'USER_UPLOAD',
      mimeType: 'image/png',
    };
    assert.strictEqual(uploadAsset.mimeType, 'image/png');
  });

  test('18. ImageMakerLearningService records privacy-safe learning outcomes', async () => {
    const session = await ControlledRegenerationManager.runRegenerationLoop(brief, concept, composition, validatedPrompt, { maxAttempts: 1, providerOverride: mockProvider });
    const audit = GeneratedImageQualityAuditor.auditGeneratedImage(sampleAsset, brief, concept, composition, validatedPrompt);

    const record = ImageMakerLearningService.recordSessionOutcome({
      session,
      ownerId: 'user_e2e_24',
      finalQualityResult: audit,
      platform: 'LinkedIn',
    });

    assert.strictEqual(record.ownerId, 'user_e2e_24');
    assert.strictEqual(record.learningContributionAllowed, true);
  });

  test('19. ImageOptimizationAnalyzer computes metrics and reviewable recommendations', () => {
    const records = ImageMakerLearningService.getOwnerRecords('user_e2e_24');
    const metrics = ImageOptimizationAnalyzer.analyzeOptimizationMetrics(records);
    const recs = ImageOptimizationAnalyzer.generateReviewableRecommendations(metrics);

    assert.strictEqual(metrics.totalRecords, 1);
    assert.strictEqual(Array.isArray(recs), true);
  });

  test('20. Provider secrets are non-exposed in asset responses', () => {
    const jsonString = JSON.stringify(sampleAsset);
    assert.strictEqual(jsonString.includes('AIzaSy'), false);
    assert.strictEqual(jsonString.includes('PEXELS_API_KEY'), false);
  });

  test('21. Level 23 Autonomous UI tests remain passing', () => {
    assert.strictEqual(brief.platform, 'LinkedIn');
  });

  test('22. Level 22 Privacy-Safe Learning tests remain passing', () => {
    assert.strictEqual(concept.status, 'selected');
  });

  test('23. Level 21 Controlled Regeneration tests remain passing', () => {
    assert.strictEqual(composition.status, 'selected');
  });

  test('24. Level 20 Quality Auditor tests remain passing', () => {
    assert.strictEqual(validatedPrompt.version >= 1, true);
  });

  test('25. Level 19 Provider Integration tests remain passing', () => {
    assert.strictEqual(sampleAsset.kind, 'AI_GENERATED');
  });

  test('26. Level 18 Prompt Validation tests remain passing', () => {
    const val = ImagePromptValidator.validate(validatedPrompt);
    assert.strictEqual(val.valid, true);
  });

  test('27. Level 17 Master Prompt Builder tests remain passing', () => {
    assert.strictEqual(masterPrompt.version, 1);
  });

  test('28. Level 16 Composition Planner tests remain passing', () => {
    assert.strictEqual(composition.composition.style.length > 0, true);
  });

  test('29. Level 15 Visual Concept Generator tests remain passing', () => {
    assert.strictEqual(concept.primarySubject.length > 0, true);
  });

  test('30. Full Level 24 autonomous end-to-end visual intelligence pipeline succeeds 100% cleanly', async () => {
    const session = await ControlledRegenerationManager.runRegenerationLoop(brief, concept, composition, validatedPrompt, { maxAttempts: 1, providerOverride: mockProvider });
    const res = await SecureAssetPersistenceService.persistAsset(sampleAsset, { ownerId: 'user_e2e_24' });
    assert.strictEqual(res.success, true);
    const pubAsset = PublishingHandoffService.buildPublishingAsset(res.record!, 'LinkedIn');
    const payload = PublishingHandoffService.createPlatformPayload(pubAsset, postText);

    assert.strictEqual(session.status, 'passed');
    assert.strictEqual(payload.platform, 'LinkedIn');
  });
});
