import { ImageGenerationProvider } from './ImageGenerationProvider';
import { ImageAssetResult } from '@/providers/canonical-image-model';
import { AIImageGenerationRequest, AIImageGenerationResponse } from './ai-provider-adapter.types';
import { AIImageGenerationRequestSchema, AIImageGenerationResponseSchema } from './ai-provider-adapter.schema';

export class AIProviderAdapter {
  /**
   * Adapts a canonical AIImageGenerationRequest, invokes the real provider, and returns a validated AIImageGenerationResponse.
   */
  public static async executeGeneration(request: AIImageGenerationRequest): Promise<AIImageGenerationResponse> {
    if (!request || !request.prompt) {
      throw new Error('INVALID_ADAPTER_REQUEST: AIImageGenerationRequest and valid prompt are required.');
    }

    AIImageGenerationRequestSchema.parse(request);

    const startedAt = new Date().toISOString();
    const prompt = request.prompt;
    const aspectRatio = request.aspectRatio || prompt.platform?.aspectRatio || '1:1';
    const { width: defaultW, height: defaultH } = ImageGenerationProvider.getDimensionsFromAspectRatio(aspectRatio);
    const width = request.width || defaultW;
    const height = request.height || defaultH;
    const seed = request.seed || Math.floor(Math.random() * 1000000);

    const providerName = request.providerPreference || prompt.providerTarget || 'pollinations_ai';
    const modelName = providerName === 'pollinations_ai' ? 'FLUX.1-schnell' : 'SDXL-Turbo';

    // Invoke underlying real ImageGenerationProvider
    const rawResult = await ImageGenerationProvider.generateImage(prompt.promptText, {
      width,
      height,
      aspectRatio,
      seed,
      versionId: prompt.id,
    });

    const completedAt = new Date().toISOString();

    // Construct Canonical ImageAssetResult
    const canonicalAsset: ImageAssetResult = {
      id: `ai_asset_${Date.now()}_${seed}`,
      source: 'POLLINATIONS_AI',
      kind: 'AI_GENERATED',
      url: rawResult.url || `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt.promptText)}?width=${width}&height=${height}`,
      previewUrl: rawResult.url || `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt.promptText)}?width=${width}&height=${height}`,
      thumbnailUrl: rawResult.url || `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt.promptText)}?width=${width}&height=${height}`,
      base64: rawResult.base64 || '',
      width,
      height,
      aspectRatio,
      mimeType: rawResult.inlineData?.mimeType || 'image/png',
      altText: prompt.concisePromptSummary || prompt.subject.primary,
      creator: { name: 'Pollinations AI Engine', url: 'https://pollinations.ai' },
      sourcePage: rawResult.url || 'https://pollinations.ai',
      attribution: {
        text: `Generated by Pollinations AI (${modelName})`,
        url: 'https://pollinations.ai',
      },
      license: 'Pollinations Open AI License',
    };

    const response: AIImageGenerationResponse = {
      asset: canonicalAsset,
      provider: providerName,
      model: modelName,
      requestId: `req_${Date.now()}_${seed}`,
      seed,
      width,
      height,
      mimeType: canonicalAsset.mimeType,
      fileSize: rawResult.base64 ? Math.round((rawResult.base64.length * 3) / 4) : undefined,
      promptVersion: prompt.version,
      briefId: prompt.briefId,
      conceptId: prompt.conceptId,
      compositionPlanId: prompt.compositionPlanId,
      generationStartedAt: startedAt,
      generationCompletedAt: completedAt,
      providerMetadata: {
        negativePromptUsed: prompt.negativePromptText || '',
        fingerprint: prompt.deterministicFingerprint,
      },
    };

    AIImageGenerationResponseSchema.parse(response);

    return response;
  }
}
