import { z } from 'zod';

export const CameraViewpointDecisionSchema = z.object({
  shotType: z.enum([
    'close_up',
    'medium_close_up',
    'medium_shot',
    'full_shot',
    'wide_shot',
    'extreme_wide',
    'macro',
    'aerial_drone',
  ]),
  cameraDistance: z.enum([
    'macro',
    'extreme_close_up',
    'close_up',
    'medium',
    'long_shot',
    'extreme_long_shot',
  ]),
  viewpoint: z.enum([
    'eye_level',
    'low_angle',
    'high_angle',
    'birds_eye',
    'worms_eye',
    'over_the_shoulder',
    'dutch_angle',
    'first_person',
  ]),
  lensCharacteristic: z.enum([
    'wide_angle_24mm',
    'standard_prime_35mm',
    'nifty_fifty_50mm',
    'portrait_85mm',
    'telephoto_135mm',
    'macro_100mm',
    'anamorphic',
    'tilt_shift',
  ]),
  cameraHeight: z.string(),
  cameraAngle: z.string(),
  focalEmphasis: z.enum([
    'shallow_depth_of_field',
    'deep_focus',
    'rack_focus',
    'bokeh_priority',
    'sharp_subject_only',
  ]),
  depthOfFieldIntent: z.string(),
  platformFraming: z.string(),
  rationale: z.string(),
  isPhysicallyCoherent: z.boolean(),
  contradictionWarnings: z.array(z.string()).optional(),
  deterministicFingerprint: z.string(),
});
