import { z } from 'zod';
import type { ExternalImageAsset } from './external-image-provider.interface';
import type { PostVisualBrief } from '@/lib/ai-image-generator/images/image.types';

export type ImageAssetKind = 'STOCK' | 'AI_GENERATED' | 'USER_UPLOAD';

export interface ImageAssetCreator {
  name: string;
  url?: string;
}

export interface ImageAssetAttribution {
  text: string;
  url: string;
}

export interface ImageAssetResult {
  id: string;
  source: string; // 'PEXELS' | 'PIXABAY' | 'UNSPLASH' | 'POLLINATIONS_AI' | 'GEMINI' | string
  kind: ImageAssetKind;
  url: string;
  previewUrl: string;
  thumbnailUrl: string;
  width: number;
  height: number;
  aspectRatio: string;
  mimeType: string;
  altText: string;
  creator: ImageAssetCreator;
  sourcePage: string;
  attribution: ImageAssetAttribution;
  license: string;
  prompt?: string;
  base64?: string;
  downloadLocation?: string;
  visualBrief?: PostVisualBrief;
  providerMetadata?: any;
}

export const ImageAssetCreatorSchema = z.object({
  name: z.string(),
  url: z.string().optional(),
});

export const ImageAssetAttributionSchema = z.object({
  text: z.string(),
  url: z.string(),
});

export const ImageAssetResultSchema = z.object({
  id: z.string().min(1),
  source: z.string().min(1),
  kind: z.enum(['STOCK', 'AI_GENERATED', 'USER_UPLOAD']),
  url: z.string().min(1),
  previewUrl: z.string(),
  thumbnailUrl: z.string(),
  width: z.number().positive(),
  height: z.number().positive(),
  aspectRatio: z.string(),
  mimeType: z.string(),
  altText: z.string(),
  creator: ImageAssetCreatorSchema,
  sourcePage: z.string(),
  attribution: ImageAssetAttributionSchema,
  license: z.string(),
  prompt: z.string().optional(),
  base64: z.string().optional(),
  downloadLocation: z.string().optional(),
  providerMetadata: z.any().optional(),
});

/**
 * Transforms an ExternalImageAsset into a canonical ImageAssetResult.
 */
export function externalAssetToCanonical(asset: ExternalImageAsset): ImageAssetResult {
  return {
    id: asset.id,
    source: (asset.provider || (asset as any).source || 'PEXELS').toUpperCase(),
    kind: 'STOCK',
    url: asset.sourceImageUrl || asset.url,
    previewUrl: asset.url,
    thumbnailUrl: asset.thumbnailUrl || asset.url,
    width: asset.width,
    height: asset.height,
    aspectRatio: asset.width === asset.height ? '1:1' : asset.width > asset.height ? '16:9' : '9:16',
    mimeType: 'image/jpeg',
    altText: asset.altText || `${asset.provider || (asset as any).source || 'PEXELS'} photo by ${asset.photographerName || 'Contributor'}`,
    creator: {
      name: asset.photographerName,
      url: asset.photographerUrl,
    },
    sourcePage: asset.attributionUrl || asset.url,
    attribution: {
      text: asset.attributionText || `Photo by ${asset.photographerName} on ${asset.provider}`,
      url: asset.attributionUrl || asset.url,
    },
    license: `${asset.provider} License`,
    downloadLocation: (asset as any).downloadLocation,
  };
}

/**
 * Transforms a raw AI generation result into a canonical ImageAssetResult.
 */
export function aiResultToCanonical(aiData: {
  id?: string;
  url: string;
  prompt: string;
  width?: number;
  height?: number;
  aspectRatio?: string;
  source?: string;
  provider?: string;
  mimeType?: string;
  base64?: string;
}): ImageAssetResult {
  const w = aiData.width || 1024;
  const h = aiData.height || 1024;
  const provider = aiData.source || aiData.provider || 'POLLINATIONS_AI';

  return {
    id: aiData.id || `ai_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
    source: provider.toUpperCase(),
    kind: 'AI_GENERATED',
    url: aiData.url,
    previewUrl: aiData.url,
    thumbnailUrl: aiData.url,
    width: w,
    height: h,
    aspectRatio: aiData.aspectRatio || (w === h ? '1:1' : w > h ? '16:9' : '9:16'),
    mimeType: aiData.mimeType || 'image/png',
    altText: aiData.prompt,
    creator: {
      name: `${provider} Engine`,
      url: 'https://minipostapp.space',
    },
    sourcePage: aiData.url,
    attribution: {
      text: `Generated by ${provider} Engine`,
      url: 'https://minipostapp.space',
    },
    license: 'AI Generated License',
    prompt: aiData.prompt,
    base64: aiData.base64,
  };
}
