import { NextRequest, NextResponse } from 'next/server';
import { ImageGenerationProvider } from '@/lib/ai-image-generator/images/ImageGenerationProvider';
import { ImageAssetResult } from '@/providers/canonical-image-model';

/**
 * Server-side AI Image Generation API Route
 * Invokes real server-side ImageGenerationProvider (Pollinations AI / Gemini)
 * Returns genuine canonical ImageAssetResult containing real image URL and base64 payload.
 */
export async function POST(req: NextRequest) {
  try {
    const body = await req.json().catch(() => ({}));
    const prompt = (body.prompt || body.imagePrompt || '').trim();
    const aspectRatio = body.aspectRatio || body.imageAspectRatio || '1:1';
    const seed = body.seed || Math.floor(Math.random() * 1000000);

    if (!prompt) {
      return NextResponse.json(
        { error: 'EMPTY_PROMPT', message: 'Prompt is required for AI image generation.' },
        { status: 400 }
      );
    }

    const { width, height } = ImageGenerationProvider.getDimensionsFromAspectRatio(aspectRatio);

    const raw = await ImageGenerationProvider.generateImage(prompt, {
      width,
      height,
      aspectRatio,
      seed,
    });

    const aiAsset: ImageAssetResult = {
      id: `ai_${Date.now()}_${raw.seed}`,
      source: 'POLLINATIONS_AI',
      kind: 'AI_GENERATED',
      url: raw.url || `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=${width}&height=${height}`,
      previewUrl: raw.url || `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=${width}&height=${height}`,
      thumbnailUrl: raw.url || `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=${width}&height=${height}`,
      base64: raw.base64 || '',
      width,
      height,
      aspectRatio,
      mimeType: raw.inlineData?.mimeType || 'image/png',
      altText: prompt,
      creator: { name: 'Pollinations AI Engine', url: 'https://pollinations.ai' },
      sourcePage: raw.url || 'https://pollinations.ai',
      attribution: {
        text: 'Generated by Pollinations AI Engine (FLUX.1 Model)',
        url: 'https://pollinations.ai',
      },
      license: 'Pollinations Open AI License',
    };

    return NextResponse.json({
      success: true,
      asset: aiAsset,
      seed: raw.seed,
      versionId: raw.versionId,
      aiProvider: 'Pollinations AI',
      aiModel: 'FLUX.1 / SDXL',
    });
  } catch (err: any) {
    return NextResponse.json(
      {
        error: 'AI_GENERATION_FAILED',
        message: err.message || 'Server-side AI image generation failed.',
      },
      { status: 500 }
    );
  }
}
