import { PlatformRules, StudioPlatform } from '../models/ai.types';

export class PlatformStrategy {
  static getRules(platform: StudioPlatform): PlatformRules {
    const all = this.buildAllRules();
    return all[platform] || all['LinkedIn'];
  }

  static getAllRules(platforms: StudioPlatform[]): Record<string, PlatformRules> {
    return Object.fromEntries(platforms.map((p) => [p, this.getRules(p)]));
  }

  private static buildAllRules(): Record<StudioPlatform, PlatformRules> {
    return {
      'LinkedIn': {
        platform: 'LinkedIn',
        maxChars: 3000,
        hookRequired: true,
        hashtagMin: 3,
        hashtagMax: 5,
        hashtagPosition: 'end',
        emojiAllowed: true,
        preferredLength: 'long',
        contentPersonality: 'Executive authority and professional thought leadership. Teach, inspire, and provoke professional thinking.',
        ctaStyle: 'Open-ended professional question ("What has been your experience with...?")',
        postStructure: ['1-2 line hook', 'Context paragraph', 'Core insight (3-5 bullet points)', 'Takeaway statement', 'Discussion question CTA', '3-5 hashtags'],
        writingStyle: 'Professional, structured, data-referenced. Avoid buzzword overuse. Break into short paragraphs for mobile reading.',
        uniqueFeatures: ['Carousel posts perform well', 'First 3 lines must compel "see more" click', 'Tag industry experts sparingly'],
      },
      'Twitter (X)': {
        platform: 'Twitter (X)',
        maxChars: 280,
        hookRequired: true,
        hashtagMin: 0,
        hashtagMax: 2,
        hashtagPosition: 'end',
        emojiAllowed: true,
        preferredLength: 'micro',
        contentPersonality: 'Real-time, punchy, opinionated. Every word must earn its place. Stop scrolling with the first sentence.',
        ctaStyle: 'Engagement prompt ("Agree?", "Thoughts?", "RT if you agree")',
        postStructure: ['Hook statement (max 20 words)', 'Core point', 'Evidence or example', 'Short CTA'],
        writingStyle: 'Ultra-concise. No wasted words. Use line breaks for rhythm. One idea per tweet. End with a question or provocation.',
        uniqueFeatures: ['Thread format for complex topics', 'Reply to trending topics for visibility', 'Polls drive high engagement'],
      },
      'Instagram Feed': {
        platform: 'Instagram Feed',
        maxChars: 2200,
        hookRequired: true,
        hashtagMin: 5,
        hashtagMax: 30,
        hashtagPosition: 'end',
        emojiAllowed: true,
        preferredLength: 'medium',
        contentPersonality: 'Visual storytelling with emotional resonance. Aesthetic-first, authentic second. Hook in the first line or lose them.',
        ctaStyle: 'Save, share, or comment prompt ("Save this for later", "Tag someone who needs this")',
        postStructure: ['Visual hook line', 'Short narrative setup', 'Value delivery (3-5 points)', 'Emotional close', 'CTA', 'Hashtag block (separate from caption)'],
        writingStyle: 'Emotional, narrative, conversational. Short paragraphs. Use emojis as bullet points. End with a save/share CTA.',
        uniqueFeatures: ['First line critical — appears in feed preview', 'Hashtag block best placed after 3-5 dots', 'Carousels get 3x reach'],
      },
      'Instagram Story': {
        platform: 'Instagram Story',
        maxChars: 200,
        hookRequired: true,
        hashtagMin: 1,
        hashtagMax: 3,
        hashtagPosition: 'inline',
        emojiAllowed: true,
        preferredLength: 'micro',
        contentPersonality: 'Quick, energetic, action-oriented. Story disappears in 24h — create urgency.',
        ctaStyle: 'Swipe-up or poll interaction',
        postStructure: ['Fast hook', '1-line context', 'CTA overlay text'],
        writingStyle: 'Very short. Punchy. Often best as a question or bold statement with a swipe-up or poll.',
        uniqueFeatures: ['Polls and questions get 5x more engagement', 'Link sticker is primary CTA tool', 'Countdown sticker for events/launches'],
      },
      'Facebook': {
        platform: 'Facebook',
        maxChars: 63206,
        hookRequired: true,
        hashtagMin: 1,
        hashtagMax: 5,
        hashtagPosition: 'end',
        emojiAllowed: true,
        preferredLength: 'long',
        contentPersonality: 'Community-oriented, conversational, discussion-focused. Facebook readers expect longer, friendlier content.',
        ctaStyle: 'Comment-driving question ("What do you think?", "Has this happened to you?")',
        postStructure: ['Engaging opener', 'Story or context', 'Educational value', 'Personal or community angle', 'Question CTA'],
        writingStyle: 'Friendly, warm, community-focused. Longer form is acceptable. End with a question to drive comments.',
        uniqueFeatures: ['Groups drive higher organic reach', 'Video posts get 5x more reach', 'Photo albums outperform single images'],
      },
      'TikTok': {
        platform: 'TikTok',
        maxChars: 2200,
        hookRequired: true,
        hashtagMin: 3,
        hashtagMax: 8,
        hashtagPosition: 'end',
        emojiAllowed: true,
        preferredLength: 'short',
        contentPersonality: 'Raw, authentic, fast-paced, energetic. Hook in the first second. Trending audio + relatable content = viral potential.',
        ctaStyle: 'Follow, comment, or stitch prompt',
        postStructure: ['Viral hook (first 1-3 seconds)', 'Scene 1: Problem', 'Scene 2: Build', 'Scene 3: Payoff/reveal', 'CTA + hashtags'],
        writingStyle: 'Video script style. Conversational. Direct address to camera. Use POV framing. Short scenes.',
        uniqueFeatures: ['First 1-3 seconds decide everything', 'Trending sounds multiply reach by 5-10x', 'Stitch and Duet increase discovery'],
      },
      'YouTube': {
        platform: 'YouTube',
        maxChars: 5000,
        hookRequired: true,
        hashtagMin: 3,
        hashtagMax: 15,
        hashtagPosition: 'end',
        emojiAllowed: true,
        preferredLength: 'long',
        contentPersonality: 'Educational authority and entertainment. YouTube rewards watch time. Hook in 30 seconds.',
        ctaStyle: 'Subscribe, like, and notification bell',
        postStructure: ['Title hook', 'Video intro script', 'Main content breakdown', 'Key chapters', 'Subscribe CTA'],
        writingStyle: 'Script-style for Shorts or full-length. Chapters improve watch time. Description should include keywords for search.',
        uniqueFeatures: ['SEO-optimized titles and descriptions', 'Chapters improve watch time', 'End screen cards'],
      },
      'Threads': {
        platform: 'Threads',
        maxChars: 500,
        hookRequired: true,
        hashtagMin: 0,
        hashtagMax: 3,
        hashtagPosition: 'end',
        emojiAllowed: true,
        preferredLength: 'short',
        contentPersonality: 'Hot takes, opinions, conversations. Threads rewards authentic, unpolished thoughts. Reply-driven engagement.',
        ctaStyle: 'Opinion prompt or reply invitation',
        postStructure: ['Hot take or opinion', 'Brief reasoning', 'Open-ended question'],
        writingStyle: 'Conversational and opinionated. Not polished. Read like a thought, not a press release.',
        uniqueFeatures: ['Replies visible to all followers', 'Reposts with comments drive discovery', 'Less hashtag-dependent than Instagram'],
      },
      'Bluesky': {
        platform: 'Bluesky',
        maxChars: 300,
        hookRequired: true,
        hashtagMin: 0,
        hashtagMax: 2,
        hashtagPosition: 'end',
        emojiAllowed: true,
        preferredLength: 'micro',
        contentPersonality: 'Decentralized, open web community. Tech-savvy, creator-forward audience. Authenticity over polish.',
        ctaStyle: 'Repost and open discussion invite',
        postStructure: ['Sharp observation', 'Context', 'Repost CTA'],
        writingStyle: 'Similar to early Twitter culture. Thoughtful, community-minded, original perspective.',
        uniqueFeatures: ['Custom feeds by interest', 'Starter packs for discovery', 'Open source community values'],
      },
      'Telegram': {
        platform: 'Telegram',
        maxChars: 4096,
        hookRequired: true,
        hashtagMin: 1,
        hashtagMax: 5,
        hashtagPosition: 'end',
        emojiAllowed: true,
        preferredLength: 'medium',
        contentPersonality: 'Channel broadcast or group discussion. Private community feel. Value-dense content expected.',
        ctaStyle: 'Forward to network or join group CTA',
        postStructure: ['Broadcast opener', 'Core value content', 'Actionable takeaway', 'Forward CTA'],
        writingStyle: 'Direct channel dispatch style. Dense value. Formatted with bold and emojis for scanability.',
        uniqueFeatures: ['Bold and italic markdown supported', 'Forwarding is primary distribution', 'Pinned messages for evergreen content'],
      },
      'Google Business': {
        platform: 'Google Business',
        maxChars: 1500,
        hookRequired: false,
        hashtagMin: 0,
        hashtagMax: 0,
        hashtagPosition: 'end',
        emojiAllowed: false,
        preferredLength: 'short',
        contentPersonality: 'Local business authority. Trust-building, professional, local SEO optimized.',
        ctaStyle: 'Call now, visit website, or book appointment',
        postStructure: ['Business update or offer', 'Value statement', 'Local relevance', 'Clear business CTA'],
        writingStyle: 'Professional, concise, factual. No hashtags. No emojis. SEO-optimized for local search.',
        uniqueFeatures: ['Photos dramatically increase engagement', 'Google Posts expire after 7 days', 'Offers and events have dedicated post types'],
      },
      'Pinterest': {
        platform: 'Pinterest',
        maxChars: 500,
        hookRequired: true,
        hashtagMin: 2,
        hashtagMax: 5,
        hashtagPosition: 'end',
        emojiAllowed: false,
        preferredLength: 'short',
        contentPersonality: 'Aspirational, discovery-focused, visually descriptive. Pinterest is a search engine for ideas.',
        ctaStyle: 'Save for later or visit link',
        postStructure: ['Aspirational description', 'What they will get', 'SEO keywords', 'Link CTA'],
        writingStyle: 'Keyword-rich for discoverability. Aspirational tone. Describes the value of the linked content.',
        uniqueFeatures: ['Vertical images (2:3) dramatically outperform', 'Rich pins auto-import metadata', 'SEO keywords in title and description critical'],
      },
    };
  }
}
