import { ToneConfig, StudioTone } from '../models/ai.types';

export class ToneEngine {
  static configure(tone: StudioTone): ToneConfig {
    const configs: Record<StudioTone, ToneConfig> = {
      'Professional': {
        tone: 'Professional',
        vocabularyStyle: 'Business-grade vocabulary. Use industry terminology. Avoid slang and colloquialisms.',
        sentenceStructure: 'authoritative',
        emojiPolicy: 'minimal',
        ctaStyle: 'Discussion or insight-sharing invitation',
        forbiddenWords: ['awesome', 'amazing', 'super', 'guys', 'gonna', 'wanna', 'stuff', 'things'],
        powerWords: ['strategic', 'enterprise', 'proven', 'optimized', 'scalable', 'measurable', 'results-driven'],
        hookStyle: 'Provocative insight or bold statement backed by data',
      },
      'Friendly': {
        tone: 'Friendly',
        vocabularyStyle: 'Warm, approachable language. Use "you" frequently. Conversational and relatable.',
        sentenceStructure: 'flowing',
        emojiPolicy: 'moderate',
        ctaStyle: 'Invitation to share or connect personally',
        forbiddenWords: ['leverage', 'synergy', 'paradigm', 'utilize', 'facilitate'],
        powerWords: ['simple', 'easy', 'imagine', 'discover', 'transform', 'together', 'you'],
        hookStyle: 'Relatable personal scenario or question',
      },
      'Corporate': {
        tone: 'Corporate',
        vocabularyStyle: 'Formal corporate language. Third-person references acceptable. Data-driven statements.',
        sentenceStructure: 'authoritative',
        emojiPolicy: 'none',
        ctaStyle: 'Professional engagement or resource request',
        forbiddenWords: ['awesome', 'cool', 'wow', 'crazy', 'unbelievable'],
        powerWords: ['enterprise', 'compliance', 'governance', 'ROI', 'KPI', 'benchmark', 'stakeholder'],
        hookStyle: 'Industry statistic or executive-level insight',
      },
      'Luxury': {
        tone: 'Luxury',
        vocabularyStyle: 'Exclusive, refined language. Evoke prestige and craftsmanship. Short, confident sentences.',
        sentenceStructure: 'concise',
        emojiPolicy: 'none',
        ctaStyle: 'Exclusive invitation or discover more',
        forbiddenWords: ['cheap', 'affordable', 'budget', 'deal', 'discount', 'sale', 'cheap alternative'],
        powerWords: ['exclusive', 'curated', 'artisan', 'bespoke', 'premier', 'refined', 'unparalleled'],
        hookStyle: 'Aspirational statement that evokes desire',
      },
      'Casual': {
        tone: 'Casual',
        vocabularyStyle: 'Everyday language. Keep it simple, light, and fun. Use contractions freely.',
        sentenceStructure: 'punchy',
        emojiPolicy: 'moderate',
        ctaStyle: 'Casual invite to engage or share',
        forbiddenWords: ['pursuant to', 'aforementioned', 'in accordance with', 'herein'],
        powerWords: ['real', 'honest', 'quick', 'simple', 'drop', 'literally', 'just'],
        hookStyle: 'Honest personal observation or fun scenario',
      },
      'Educational': {
        tone: 'Educational',
        vocabularyStyle: 'Clear, instructive language. Define technical terms. Use numbered lists and structured breakdowns.',
        sentenceStructure: 'flowing',
        emojiPolicy: 'minimal',
        ctaStyle: 'Learn more or follow for more insights',
        forbiddenWords: ['obviously', 'clearly', 'as everyone knows'],
        powerWords: ['learn', 'understand', 'discover', 'master', 'step-by-step', 'breakdown', 'explain'],
        hookStyle: 'Knowledge gap or surprising fact',
      },
      'Funny': {
        tone: 'Funny',
        vocabularyStyle: 'Witty, light-hearted language. Use wordplay and relatable humor. Avoid forced jokes.',
        sentenceStructure: 'punchy',
        emojiPolicy: 'heavy',
        ctaStyle: 'Tag a friend or share the laugh',
        forbiddenWords: ['synergy', 'leverage', 'paradigm shift'],
        powerWords: ['plot twist', 'real talk', 'no one told me', 'honestly', 'unpopular opinion'],
        hookStyle: 'Unexpected twist or humorous observation',
      },
      'Bold': {
        tone: 'Bold',
        vocabularyStyle: 'Confident, direct language. Short punchy sentences. Challenge the status quo.',
        sentenceStructure: 'punchy',
        emojiPolicy: 'minimal',
        ctaStyle: 'Challenge or call to action',
        forbiddenWords: ['maybe', 'perhaps', 'might', 'could be', 'sort of'],
        powerWords: ['stop', 'wake up', 'truth', 'proven', 'guaranteed', 'dominate', 'crush', 'win'],
        hookStyle: 'Bold contrarian statement or challenge',
      },
      'Inspirational': {
        tone: 'Inspirational',
        vocabularyStyle: 'Uplifting, motivational language. Paint a vision. Use storytelling.',
        sentenceStructure: 'flowing',
        emojiPolicy: 'moderate',
        ctaStyle: 'Share your journey or save for motivation',
        forbiddenWords: ['failure', 'impossible', 'never', 'can\'t'],
        powerWords: ['imagine', 'possible', 'journey', 'transform', 'rise', 'believe', 'potential'],
        hookStyle: 'Transformation narrative or vision statement',
      },
      'Technical': {
        tone: 'Technical',
        vocabularyStyle: 'Precise technical language. Use exact terminology. Code-level accuracy expected.',
        sentenceStructure: 'authoritative',
        emojiPolicy: 'none',
        ctaStyle: 'Share your implementation or discuss in comments',
        forbiddenWords: ['simple', 'easy', 'just', 'merely', 'obviously'],
        powerWords: ['architecture', 'implementation', 'optimization', 'algorithm', 'scalability', 'latency'],
        hookStyle: 'Technical problem statement or counterintuitive finding',
      },
      'Minimal': {
        tone: 'Minimal',
        vocabularyStyle: 'Fewer words. Maximum impact. No filler. Every word earns its place.',
        sentenceStructure: 'concise',
        emojiPolicy: 'none',
        ctaStyle: 'One clear action',
        forbiddenWords: ['very', 'really', 'actually', 'basically', 'essentially', 'literally'],
        powerWords: ['clarity', 'focus', 'essential', 'core', 'precise'],
        hookStyle: 'Single powerful statement',
      },
    };
    return configs[tone];
  }
}
