import { HelpItem } from '../types/explain-item.types';

export const GLOBAL_HELP_ITEMS: HelpItem[] = [
  {
    id: 'global-nav-features',
    title: 'Product Features Navigation',
    shortDescription: 'Explores AI multi-channel publishing capabilities.',
    purpose: 'Navigates to the product features breakdown and engine overview.',
    instructions: ['Click to open the features page.', 'Review platform capabilities and AI workflows.'],
    expectedResult: 'Navigates cleanly to /company/product/features.',
    category: 'NAVIGATION',
    route: 'Global Header',
    placement: 'BELOW',
    version: 'v1.0.0',
    reviewed: true,
  },
  {
    id: 'global-nav-pricing',
    title: 'Pricing & Subscriptions',
    shortDescription: 'Displays subscription tier details and Stripe checkout options.',
    purpose: 'Allows creators and agencies to choose suitable usage tiers.',
    instructions: ['Click to view subscription pricing options.'],
    expectedResult: 'Navigates to /subscribe.',
    category: 'NAVIGATION',
    route: 'Global Header',
    placement: 'BELOW',
    version: 'v1.0.0',
    reviewed: true,
  },
  {
    id: 'global-nav-company',
    title: 'Company Overview',
    shortDescription: 'Learn about Mini Post App, team, and operating entity Yoga Products Top Limited.',
    purpose: 'Provides background on corporate identity and vision.',
    instructions: ['Click to view company background.'],
    expectedResult: 'Navigates to /company/about.',
    category: 'NAVIGATION',
    route: 'Global Header',
    placement: 'BELOW',
    version: 'v1.0.0',
    reviewed: true,
  },
  {
    id: 'global-nav-trust-safety',
    title: 'Trust & Safety Center',
    shortDescription: 'Access engineering standards, data protection rules, and platform compliance.',
    purpose: 'Displays 31 public standards and security commitments.',
    instructions: ['Click to view the Trust & Safety center.'],
    expectedResult: 'Navigates to /company/trust/trust-safety.',
    category: 'NAVIGATION',
    route: 'Global Header',
    placement: 'BELOW',
    version: 'v1.0.0',
    reviewed: true,
  },
];
