import { getPublicEngineeringStandards, PublicStandardSummary } from '@/standards/adapters/public-standards.adapter';

export type StandardSourceType = 'INTERNAL' | 'PLATFORM_REFERENCE' | 'INDUSTRY_REFERENCE' | 'INTERNATIONAL_REFERENCE' | 'LEGAL_REFERENCE';

export type StandardCategory =
  | 'Internal Engineering'
  | 'AI and Content'
  | 'Design System'
  | 'Social Platform'
  | 'Video'
  | 'Publishing'
  | 'Accessibility'
  | 'Compliance';

export interface EngineeringStandard {
  id: string;
  order: number;
  name: string;
  reference: string;
  implementation: string;
  publishedBy: string;
  category: StandardCategory;
  sourceType: StandardSourceType;
}

// Fallback standards dataset derived cleanly from canonical Standards System
const FALLBACK_ENGINEERING_STANDARDS: EngineeringStandard[] = [
  {
    id: 'quality-standard',
    order: 1,
    name: 'Quality Standard',
    reference: 'Informed by ISO/IEC 25010 (2023 Edition) & Mini Post App v1.0',
    implementation: 'Defines measurable content quality, review pipeline, scoring and acceptance criteria.',
    publishedBy: 'Mini Post App',
    category: 'Internal Engineering',
    sourceType: 'INTERNAL',
  },
  {
    id: 'ai-governance-standard',
    order: 2,
    name: 'AI Governance Standard',
    reference: 'Informed by ISO/IEC 42001 (2023 Edition) & NIST AI RMF 1.0',
    implementation: 'Governs AI text and image prompt safety, human oversight, transparency, and auditability.',
    publishedBy: 'Mini Post App',
    category: 'AI and Content',
    sourceType: 'INTERNATIONAL_REFERENCE',
  },
  {
    id: 'ai-writing-standard',
    order: 3,
    name: 'AI Writing Standard',
    reference: 'Mini Post App Internal Standard v1.0',
    implementation: 'Governs AI writing style, tone, structure, grammar and readability.',
    publishedBy: 'Mini Post App',
    category: 'AI and Content',
    sourceType: 'INTERNAL',
  },
  {
    id: 'prompt-standard',
    order: 4,
    name: 'Prompt Standard',
    reference: 'Mini Post App Internal Standard v1.0',
    implementation: 'Defines how prompts are generated, validated and optimized.',
    publishedBy: 'Mini Post App',
    category: 'AI and Content',
    sourceType: 'INTERNAL',
  },
  {
    id: 'image-standard',
    order: 5,
    name: 'Image Standard',
    reference: 'Mini Post App Internal Standard v1.0',
    implementation: 'Controls image quality, composition, branding and generation workflow.',
    publishedBy: 'Mini Post App',
    category: 'AI and Content',
    sourceType: 'INTERNAL',
  },
  {
    id: 'typography-standard',
    order: 6,
    name: 'Typography Standard',
    reference: 'Mini Post App Internal Standard v1.0',
    implementation: 'Defines font hierarchy, spacing, sizing and readability.',
    publishedBy: 'Mini Post App',
    category: 'Design System',
    sourceType: 'INTERNAL',
  },
  {
    id: 'color-standard',
    order: 7,
    name: 'Color Standard',
    reference: 'Mini Post App Internal Standard v1.0',
    implementation: 'Defines brand colors, contrast, accessibility and palette usage.',
    publishedBy: 'Mini Post App',
    category: 'Design System',
    sourceType: 'INTERNAL',
  },
  {
    id: 'hierarchy-standard',
    order: 8,
    name: 'Hierarchy Standard',
    reference: 'Mini Post App Internal Standard v1.0',
    implementation: 'Defines visual hierarchy, 3D depth, emphasis and layout priority.',
    publishedBy: 'Mini Post App',
    category: 'Design System',
    sourceType: 'INTERNAL',
  },
  {
    id: 'spacing-standard',
    order: 9,
    name: 'Spacing Standard',
    reference: 'Mini Post App Internal Standard v1.0',
    implementation: 'Defines margins, padding, whitespace and component spacing.',
    publishedBy: 'Mini Post App',
    category: 'Design System',
    sourceType: 'INTERNAL',
  },
  {
    id: 'ui-standard',
    order: 10,
    name: 'UI Standard',
    reference: 'Mini Post App Internal Standard v1.0',
    implementation: 'Defines interface consistency and component behavior.',
    publishedBy: 'Mini Post App',
    category: 'Design System',
    sourceType: 'INTERNAL',
  },
  {
    id: 'facebook-standard',
    order: 11,
    name: 'Facebook Standard',
    reference: 'Meta Platform Guidelines + Mini Post App',
    implementation: 'Facebook post formatting, limits, media and engagement optimization.',
    publishedBy: 'Meta / Mini Post App',
    category: 'Social Platform',
    sourceType: 'PLATFORM_REFERENCE',
  },
  {
    id: 'instagram-standard',
    order: 12,
    name: 'Instagram Standard',
    reference: 'Meta Platform Guidelines + Mini Post App',
    implementation: 'Feed, Story, Carousel and Reel optimization.',
    publishedBy: 'Meta / Mini Post App',
    category: 'Social Platform',
    sourceType: 'PLATFORM_REFERENCE',
  },
  {
    id: 'linkedin-standard',
    order: 13,
    name: 'LinkedIn Standard',
    reference: 'LinkedIn Guidelines + Mini Post App',
    implementation: 'Professional content structure and publishing optimization.',
    publishedBy: 'LinkedIn / Mini Post App',
    category: 'Social Platform',
    sourceType: 'PLATFORM_REFERENCE',
  },
  {
    id: 'x-twitter-standard',
    order: 14,
    name: 'X (Twitter) Standard',
    reference: 'X Platform Guidelines + Mini Post App',
    implementation: 'Character limits, threads, hashtags and engagement.',
    publishedBy: 'X Corp. / Mini Post App',
    category: 'Social Platform',
    sourceType: 'PLATFORM_REFERENCE',
  },
  {
    id: 'threads-standard',
    order: 15,
    name: 'Threads Standard',
    reference: 'Meta Platform Guidelines + Mini Post App',
    implementation: 'Threads publishing workflow and formatting.',
    publishedBy: 'Meta / Mini Post App',
    category: 'Social Platform',
    sourceType: 'PLATFORM_REFERENCE',
  },
  {
    id: 'pinterest-standard',
    order: 16,
    name: 'Pinterest Standard',
    reference: 'Pinterest Guidelines + Mini Post App',
    implementation: 'Pin structure, SEO and image optimization.',
    publishedBy: 'Pinterest / Mini Post App',
    category: 'Social Platform',
    sourceType: 'PLATFORM_REFERENCE',
  },
  {
    id: 'youtube-standard',
    order: 17,
    name: 'YouTube Standard',
    reference: 'YouTube Creator Guidelines + Mini Post App',
    implementation: 'Video publishing, titles, descriptions and thumbnails.',
    publishedBy: 'Google / Mini Post App',
    category: 'Social Platform',
    sourceType: 'PLATFORM_REFERENCE',
  },
  {
    id: 'tiktok-standard',
    order: 18,
    name: 'TikTok Standard',
    reference: 'TikTok Creator Guidelines + Mini Post App',
    implementation: 'Short-form video optimization and publishing.',
    publishedBy: 'TikTok / Mini Post App',
    category: 'Social Platform',
    sourceType: 'PLATFORM_REFERENCE',
  },
  {
    id: 'google-business-standard',
    order: 19,
    name: 'Google Business Standard',
    reference: 'Google Business Profile Guidelines',
    implementation: 'Local business post formatting and optimization.',
    publishedBy: 'Google',
    category: 'Social Platform',
    sourceType: 'PLATFORM_REFERENCE',
  },
  {
    id: 'shorts-standard',
    order: 20,
    name: 'Shorts Standard',
    reference: 'YouTube Shorts Guidelines',
    implementation: 'Vertical video optimization and publishing.',
    publishedBy: 'Google',
    category: 'Video',
    sourceType: 'PLATFORM_REFERENCE',
  },
  {
    id: 'reels-standard',
    order: 21,
    name: 'Reels Standard',
    reference: 'Instagram & Facebook Reels Guidelines',
    implementation: 'Reel formatting, duration and optimization.',
    publishedBy: 'Meta',
    category: 'Video',
    sourceType: 'PLATFORM_REFERENCE',
  },
  {
    id: 'video-production-standard',
    order: 22,
    name: 'Video Production Standard',
    reference: 'Mini Post App Internal Standard v1.0',
    implementation: 'AI-assisted video creation and production workflow.',
    publishedBy: 'Mini Post App',
    category: 'Video',
    sourceType: 'INTERNAL',
  },
  {
    id: 'seo-standard',
    order: 23,
    name: 'SEO Standard',
    reference: 'Mini Post App Internal Standard v1.0',
    implementation: 'Metadata, keywords, search optimization and discoverability.',
    publishedBy: 'Mini Post App',
    category: 'Publishing',
    sourceType: 'INTERNAL',
  },
  {
    id: 'hashtag-standard',
    order: 24,
    name: 'Hashtag Standard',
    reference: 'Mini Post App Internal Standard v1.0',
    implementation: 'Platform-specific hashtag research and validation.',
    publishedBy: 'Mini Post App',
    category: 'Publishing',
    sourceType: 'INTERNAL',
  },
  {
    id: 'scheduling-standard',
    order: 25,
    name: 'Scheduling Standard',
    reference: 'Mini Post App Internal Standard v1.0',
    implementation: 'Publishing schedules, time zones and automation rules.',
    publishedBy: 'Mini Post App',
    category: 'Publishing',
    sourceType: 'INTERNAL',
  },
  {
    id: 'publishing-standard',
    order: 26,
    name: 'Publishing Standard',
    reference: 'Mini Post App Internal Standard v1.0',
    implementation: 'Final publishing validation and multi-platform deployment.',
    publishedBy: 'Mini Post App',
    category: 'Publishing',
    sourceType: 'INTERNAL',
  },
  {
    id: 'accessibility-standard',
    order: 27,
    name: 'Accessibility Standard',
    reference: 'Informed by WCAG 2.2 AA & Mini Post App',
    implementation: 'Accessibility validation for generated content and interface elements.',
    publishedBy: 'W3C / Mini Post App',
    category: 'Accessibility',
    sourceType: 'INDUSTRY_REFERENCE',
  },
  {
    id: 'content-policy-standard',
    order: 28,
    name: 'Content Policy Standard',
    reference: 'Platform Policies + Mini Post App',
    implementation: 'Ensures generated content complies with platform rules.',
    publishedBy: 'Platform Providers / Mini Post App',
    category: 'Compliance',
    sourceType: 'PLATFORM_REFERENCE',
  },
  {
    id: 'platform-rules-standard',
    order: 29,
    name: 'Platform Rules Standard',
    reference: 'Platform Terms & Community Guidelines',
    implementation: "Validates content against each platform's applicable rules.",
    publishedBy: 'Platform Providers',
    category: 'Compliance',
    sourceType: 'PLATFORM_REFERENCE',
  },
  {
    id: 'template-standard',
    order: 30,
    name: 'Template Standard',
    reference: 'Mini Post App Internal Standard v1.0',
    implementation: 'Defines template architecture, reusable layouts and consistency.',
    publishedBy: 'Mini Post App',
    category: 'Internal Engineering',
    sourceType: 'INTERNAL',
  },
  {
    id: 'sizing-standard',
    order: 31,
    name: 'Sizing Standard',
    reference: 'Mini Post App Internal Standard v1.0',
    implementation: 'Automatically resizes content for supported platforms and templates.',
    publishedBy: 'Mini Post App',
    category: 'Internal Engineering',
    sourceType: 'INTERNAL',
  },
];

export const ENGINEERING_STANDARDS: EngineeringStandard[] = (() => {
  const dynamicSummaries = getPublicEngineeringStandards();
  if (dynamicSummaries && dynamicSummaries.length > 0) {
    return dynamicSummaries.map((s: PublicStandardSummary) => ({
      id: s.id,
      order: s.order,
      name: s.name,
      reference: s.reference,
      implementation: s.implementation,
      publishedBy: s.publishedBy,
      category: s.category as StandardCategory,
      sourceType: s.sourceType as StandardSourceType,
    }));
  }
  return FALLBACK_ENGINEERING_STANDARDS;
})();
